get "/users", to: "users#index"
get "/users/:id", to: "users#show"
post "/users", to: "users#create"
put "/users/:id", to: "users#update"
put "/users/:id/activate", to: "users#activate"
delete "/users/:id", to: "users#delete"
